---
name: Run Test Suite

on: [pull_request]

jobs:
  run-tests-on-linux-ubuntu-2004:
    name: Run Tests on Linux (Ubuntu 20.04)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install xvfb x11-utils python3 python3-pip python3-tk
          python -m pip install --upgrade pip
          python -m pip install pyinstaller setuptools wheel twine pytest pytest-cov
          python -m pip install requests==2.25.0

      - name: Test with pytest
        run: |
          disp=:99
          screen=0
          geom=800x600x24
          exec Xvfb $disp -screen $screen $geom 2>/tmp/Xvfb.log &
          export DISPLAY=:99
          /home/runner/.local/bin/pytest
