---
name: Run Test Suite

on: [pull_request]

jobs:
  run-tests-on-linux-ubuntu-2004:
    name: Run Tests on Linux (Ubuntu 20.04)
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller setuptools wheel twine pytest pytest-cov
          python -m pip install requests==2.25.0

      - name: Test with pytest
        run: |
          pytest
